# Generated by Django 5.1 on 2024-09-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0002_alter_aboutus_options_alter_aboutus_imageabout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutOurExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('image_about', models.ImageField(upload_to='AboutOurExperience/', verbose_name='фото фона')),
                ('main_description', models.TextField(verbose_name='Описание')),
                ('first_cart_title', models.CharField(max_length=15, verbose_name='Заголовок первой карточки')),
                ('first_cart_description', models.TextField(verbose_name='Описание первой карточки')),
                ('second_cart_title', models.CharField(max_length=15, verbose_name='Заголовок второй карточки')),
                ('second_cart_description', models.TextField(verbose_name='Описание второй карточки')),
                ('third_cart_title', models.CharField(max_length=15, verbose_name='Заголовок третьей карточки')),
                ('third_cart_description', models.TextField(verbose_name='Описание третьей карточки')),
            ],
            options={
                'verbose_name': 'О нас и о нашем опыте',
                'verbose_name_plural': 'О нас и о нашем опыте',
            },
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='ImageAbout',
            new_name='Image_about',
        ),
    ]
