# Generated by Django 5.1 on 2024-09-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0003_aboutourexperience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='Image_about',
            new_name='image_about',
        ),
    ]
