# Generated by Django 5.1 on 2024-09-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0004_rename_image_about_aboutus_image_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='image_about',
            new_name='first_image',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='fifth_image',
            field=models.ImageField(blank=True, null=True, upload_to='ImageAboutUs/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='fourth_image',
            field=models.ImageField(blank=True, null=True, upload_to='ImageAboutUs/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='ImageAboutUs/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='sixth_image',
            field=models.ImageField(blank=True, null=True, upload_to='ImageAboutUs/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='third_image',
            field=models.ImageField(blank=True, null=True, upload_to='ImageAboutUs/', verbose_name='Изображение'),
        ),
    ]
