# Generated by Django 5.1 on 2024-09-07 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0006_remove_aboutus_fifth_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageaboutus',
            name='about_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='AboutUs.aboutus'),
        ),
    ]
