# Generated by Django 5.1 on 2024-09-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0007_alter_imageaboutus_about_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutourexperience',
            name='image_about',
        ),
    ]
