# Generated by Django 5.1 on 2024-09-02 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurServices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourservice',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='ourservicedetail',
            options={'verbose_name': 'Деталь услуги', 'verbose_name_plural': 'Детали услуг'},
        ),
        migrations.AlterModelOptions(
            name='ourserviceprice',
            options={'verbose_name': 'Цена услуги', 'verbose_name_plural': 'Цены услуг'},
        ),
        migrations.AddField(
            model_name='ourserviceprice',
            name='contact',
            field=models.TextField(default=1, verbose_name='Контактная информация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='ImageOurService',
            field=models.ImageField(upload_to='ImageOurService/', verbose_name='Изображение услуги'),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='title',
            field=models.CharField(max_length=34, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ourservicedetail',
            name='ImageDetailOurService',
            field=models.ImageField(upload_to='ImageOurService/', verbose_name='Изображение детали услуги'),
        ),
        migrations.AlterField(
            model_name='ourservicedetail',
            name='our_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OurServices.ourservice', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='ourservicedetail',
            name='title',
            field=models.CharField(max_length=34, verbose_name='Название детали'),
        ),
        migrations.AlterField(
            model_name='ourserviceprice',
            name='our_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OurServices.ourservicedetail', verbose_name='Деталь услуги'),
        ),
        migrations.AlterField(
            model_name='ourserviceprice',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='Цена'),
        ),
    ]
