# Generated by Django 5.1 on 2024-09-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geolocate',
            options={'verbose_name': 'Геолокация', 'verbose_name_plural': 'Геолокации'},
        ),
        migrations.AlterModelOptions(
            name='instagram',
            options={'verbose_name': 'Instagram', 'verbose_name_plural': 'Instagram'},
        ),
        migrations.AlterModelOptions(
            name='ourteam',
            options={'verbose_name': 'Член команды', 'verbose_name_plural': 'Наша команда'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='telegram',
            options={'verbose_name': 'Telegram', 'verbose_name_plural': 'Telegram'},
        ),
        migrations.AlterModelOptions(
            name='tiktok',
            options={'verbose_name': 'TikTok', 'verbose_name_plural': 'TikTok'},
        ),
        migrations.AlterModelOptions(
            name='whatsapp',
            options={'verbose_name': 'WhatsApp', 'verbose_name_plural': 'WhatsApp'},
        ),
        migrations.AlterField(
            model_name='geolocate',
            name='locate',
            field=models.TextField(verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='geolocate',
            name='map_image',
            field=models.ImageField(upload_to='MapImage/', verbose_name='Карта'),
        ),
        migrations.AlterField(
            model_name='geolocate',
            name='working_hours',
            field=models.TextField(verbose_name='Часы работы'),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='url',
            field=models.TextField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='first_name',
            field=models.CharField(max_length=18, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='last_name',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='role',
            field=models.CharField(max_length=16, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='review',
            name='first_name',
            field=models.CharField(max_length=18, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='last_name',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=1, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='telegram',
            name='url',
            field=models.TextField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='tiktok',
            name='url',
            field=models.TextField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='url',
            field=models.TextField(verbose_name='Ссылка'),
        ),
    ]
