# Generated by Django 5.1 on 2024-09-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0003_ourteam_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(default=1, upload_to='ImageReviewer', verbose_name='Фото пользователя'),
            preserve_default=False,
        ),
    ]
