# Generated by Django 5.1 on 2024-09-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0004_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(upload_to='ImageReviewer/', verbose_name='Фото пользователя'),
        ),
    ]
