# Generated by Django 5.1 on 2024-09-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0005_alter_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocate',
            name='map_url',
            field=models.TextField(default=1, verbose_name='Ссылка на местоположения'),
            preserve_default=False,
        ),
    ]
